### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by YordiSch** [YkeSmit1/BidTrainer#2]
Bij ingevoerde pbn's wordt de gever nog niet overgenomen.
Je krijgt wisselend de noord en de zuid hand. (oneven spellen N, even spellen Z)

**Comment by YordiSch** [comment]
Als je een verkeerd bod doet, geeft hij aan wat je had moeten maar, maar als dit wegklikt of bevestigt doet hij automatisch het goede bod. Misschien zijn er mogelijkheden om nog niet direct het goede bod te tonen (en voornamelijk het ze zelf te laten doen).
Als je een hint knop geeft kan je foute biedingen gewoon niet accepteren en als ze er dan niet uit komen kunnen ze via de hint zien wat ze zouden moeten bieden.

**Comment by YordiSch** [comment]
Het bieden stopt bij 3x pas. In de 4e hand kan je dus niet openen.
Je hebt Ax, xxx, Kxxx, KJxx. Is dit geen 1R bod na een 1K opening van partner (maar 2SA is een redelijk alternatief)

**Comment by YordiSch** [comment]
![image](https://user-images.githubusercontent.com/81969599/113585692-de76ff00-962c-11eb-8c8d-29cb286daeed.png)
Geen stayman?

**Comment by YordiSch** [comment]
![image](https://user-images.githubusercontent.com/81969599/113586149-707f0780-962d-11eb-9c09-f6b175886839.png)
2H kan wel een alternatief zijn voor deze hand. Maar de uitleg klopt dan niet

**Comment by YkeSmit1** [comment]
All issues should be fixed
