### ISSUE TITLE
Problemen met herbiedingen

### ISSUE THREAD

**Issue by YordiSch** [YkeSmit1/BidTrainer#5]
![image](https://user-images.githubusercontent.com/81969599/114274383-6d658c00-9a1e-11eb-8b37-19cd165e3874.png)
Lijkt me wat veel voor een pas, ook al heeft partner voorgepast.

**Comment by YordiSch** [comment]
![image](https://user-images.githubusercontent.com/81969599/114274449-b3225480-9a1e-11eb-9b61-5b9a97e8efb2.png)
Inderdaad niet genoeg voor de manche, maar wel genoeg shape om toch niet te passen.

**Comment by YordiSch** [comment]
![image](https://user-images.githubusercontent.com/81969599/114274679-f29d7080-9a1f-11eb-909c-4c003390c36b.png)
Toch wel een manche waar je in moet zitten (100% volgens mij)

**Comment by YordiSch** [comment]
![image](https://user-images.githubusercontent.com/81969599/114274847-95ee8580-9a20-11eb-93e1-b92401d2622c.png)
Een redelijke 7R, lijkt nog een systematische probleem te zijn na een 2/1

**Comment by YordiSch** [comment]
![image](https://user-images.githubusercontent.com/81969599/114274994-26c56100-9a21-11eb-9e86-494ddb080929.png)
Blijkbaar als hij te veel heeft na een 1 bod gaat hij nog passen. Dacht dat het aan de voorpas lag, maar hier weer.

**Comment by YkeSmit1** [comment]
All the issues are fixed except the first one. Reverse is not implemented (yet)
